---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cp-jobs
  description: Background job service
  annotations:
    backstage.io/techdocs-ref: dir:./docs/cp-jobs
    github.com/project-slug: Shonei/backstage-poc
    jira/project-key: AV
    # jira/component: <example-component> 
    jira/token-type: Bearer
  tags:
    - background
    - go
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
spec:
  type: service
  lifecycle: production
  owner: sre
  system: control-plane
  dependsOn: ["resource:couchbase"]
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: cp-api
  description: Client facing API for the Capella UI
  annotations:
    backstage.io/techdocs-ref: dir:./
  tags:
    - api
    - go
spec:
  type: openapi
  lifecycle: production
  owner: platform
  system: control-plane
  definition:
    $text: https://github.com/APIs-guru/openapi-directory/blob/dab6854d4d599aafb0eb36e6c7ae1fe0c37509b7/APIs/spotify.com/2021.4.2/openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: couchbase
  description: Internal database
spec:
  type: database
  lifecycle: production
  owner: platform
  system: control-plane
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: cloud
  description: The backstage sub-department
spec:
  type: sub-department
  profile:
    displayName: Cloud
    email: cloud@example.com
    picture: https://avatars.dicebear.com/api/identicon/backstage@example.com.svg?background=%23fff&margin=25
  parent: infrastructure
  children: [sre, platform]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sre
  description: sre
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: sre@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: cloud
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform
  description: platform
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: platform@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: cloud
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Teo1
spec:
  profile:
    # Intentional no displayName for testing
    email: breanna-davison@example.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [sre]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Teo1
spec:
  profile:
    # Intentional no displayName for testing
    email: breanna-davison@example.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [sre]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Teo1
spec:
  profile:
    # Intentional no displayName for testing
    email: breanna-davison@example.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [platform]
  